# encoding: utf-8
# Copyright (c) dbosoft GmbH and Haipa Contributors. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

source 'https://rubygems.org'

# Specify your gem's dependencies in haipa_rest.gemspec
gemspec

group :test do
  gem 'rspec'
end
